table Objetivos
	lineageTag: b8991549-3cba-4502-a7b5-75b310732aa2

	column Gestion
		dataType: int64
		formatString: 0
		lineageTag: e5c9a374-a524-4452-a987-6f000d3343ae
		summarizeBy: sum
		sourceColumn: Gestion

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: int64
		formatString: 0
		lineageTag: 5391fe68-16a9-4906-a900-74cbed790e95
		summarizeBy: sum
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: int64
		formatString: 0
		lineageTag: e5f8c9f6-1711-4307-9ae4-f2c3219963ca
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column Sucursal
		dataType: int64
		formatString: 0
		lineageTag: faed990a-9a73-4e7a-a478-fa96a85efe58
		summarizeBy: none
		sourceColumn: Sucursal

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 656f685d-4799-4f6f-9906-7310e4bea3b4
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Linea
		dataType: string
		lineageTag: f36a1944-b950-42b4-b3da-f37477449da9
		summarizeBy: none
		sourceColumn: Linea

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: a901a251-a533-4ecf-ae6a-fa63d6d1250b
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Objetivo
		dataType: double
		lineageTag: 975eccf8-179f-4aff-b0c5-2da960f5fba0
		summarizeBy: sum
		sourceColumn: Objetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UtilidadObj
		dataType: double
		lineageTag: 49734fa8-6c70-48b7-bcc9-e7472bbe1cf2
		summarizeBy: sum
		sourceColumn: UtilidadObj

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Periodo
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 16a2f426-c184-4be7-abc4-36b8bce3a0a7
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fechas.TC_$us'
		dataType: double
		lineageTag: 6ceb9abc-93bb-442b-8625-74c9b1045a93
		summarizeBy: sum
		sourceColumn: Fechas.TC_$us

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ObjetivoBs
		dataType: double
		lineageTag: 6ddd74d0-34e6-4e45-bb57-96b69bcedf09
		summarizeBy: sum
		sourceColumn: ObjetivoBs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UtilidadObjBs
		dataType: double
		lineageTag: 41c7b98c-d66f-4bf3-bb89-6524ea2ef8b2
		summarizeBy: sum
		sourceColumn: UtilidadObjBs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Objetivos = m
		mode: import
		source =
				let
				    Origen = Table.Combine({Objetivos2025, Objetivos2025}),
				    #"Valor reemplazado" = Table.ReplaceValue(Origen,"T. POTENCIA","T.POTENCIA",Replacer.ReplaceText,{"Linea"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","#","SERVICIOS",Replacer.ReplaceText,{"Linea"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","","SERVICIOS",Replacer.ReplaceValue,{"Linea"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado2",{{"Mes", Int64.Type}}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Tipo cambiado",null,0,Replacer.ReplaceValue,{"UtilidadObj"}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Valor reemplazado3", "Combinada", each Text.Combine({"1/", Text.From([Mes], "es-BO"), "/", Text.From([Gestion], "es-BO")}), type text),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna combinada insertada",{{"Combinada", type date}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado1",{{"Combinada", "Periodo"}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas con nombre cambiado", {"Periodo"}, Fechas, {"Fecha"}, "Fechas", JoinKind.LeftOuter),
				    #"Se expandió Fechas" = Table.ExpandTableColumn(#"Consultas combinadas", "Fechas", {"TC_$us"}, {"Fechas.TC_$us"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Se expandió Fechas", "ObjetivoBs", each [Objetivo] * [#"Fechas.TC_$us"]),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "UtilidadObjBs", each [UtilidadObj] * [#"Fechas.TC_$us"]),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"ObjetivoBs", type number}, {"UtilidadObjBs", type number}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

